name: CI

on:
  push:

env:
  PNPM_VERSION: 8.6.3

jobs:
  test:
    name: Test - Node ${{ matrix.node-version }} & ESLint ${{ matrix.eslint-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
        eslint-version: [7, 8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm test

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm type:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm build